//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatSavings
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisementType
    {
        public int AdTypeId { get; set; }
        public string AdName { get; set; }
    
        public virtual Advertisement Advertisement { get; set; }
    }
}
