//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatSavings
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessIndustry
    {
        public BusinessIndustry()
        {
            this.Merchants = new HashSet<Merchant>();
            this.Directories = new HashSet<Directory>();
        }
    
        public int BusIndustryId { get; set; }
        public string BusIndustry { get; set; }
    
        public virtual ICollection<Merchant> Merchants { get; set; }
        public virtual ICollection<Directory> Directories { get; set; }
    }
}
