//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatSavings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string TermsAndCondition { get; set; }
        public byte[] Image { get; set; }
        public int TransId { get; set; }
        public bool IsActivated { get; set; }
        public string DirId { get; set; }
    
        public virtual Transaction Transaction { get; set; }
        public virtual Directory Directory { get; set; }
    }
}
