//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatSavings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public Merchant()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int MerchantId { get; set; }
        public string CompanyName { get; set; }
        public string StreetName { get; set; }
        public int Postcode { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Website { get; set; }
        public string OperateFrom { get; set; }
        public string OperateTo { get; set; }
        public int BusIndustryId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContactNo { get; set; }
        public Nullable<bool> IsActivated { get; set; }
        public byte[] CompanyImg { get; set; }
        public string UserId { get; set; }
    
        public virtual BusinessIndustry BusinessIndustry { get; set; }
        public virtual MerchantAccount MerchantAccount { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
