//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatSavings
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantAccount
    {
        public int MerchantId { get; set; }
        public string UserId { get; set; }
    
        public virtual Merchant Merchant { get; set; }
    }
}
