//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatSavings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Payable { get; set; }
        public decimal Price { get; set; }
        public string Hint { get; set; }
        public string Description { get; set; }
        public int MaxTerm { get; set; }
        public string Term { get; set; }
        public string Currency { get; set; }
        public Nullable<short> Position { get; set; }
        public Nullable<bool> Searchable { get; set; }
    }
}
