//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatSavings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int PromotionId { get; set; }
        public int PromotionTypeId { get; set; }
        public string Title { get; set; }
        public string Desc { get; set; }
        public string ValidFrom { get; set; }
        public string ValidTo { get; set; }
        public Nullable<bool> IsNationWide { get; set; }
        public byte[] ImgThumbnail { get; set; }
        public byte[] ImgDetailPage { get; set; }
        public byte[] ImgPremiumAd { get; set; }
    
        public virtual PromotionsType PromotionsType { get; set; }
    }
}
