//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatSavings
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionsType
    {
        public PromotionsType()
        {
            this.Promotions = new HashSet<Promotion>();
        }
    
        public int PromotionsTypeId { get; set; }
        public string PromotionsType1 { get; set; }
    
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}
